fixing the version of docutils to prevent error during the build
```
Exception occurred:
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 882, in interpreted
    nodes[0][0].rawsource = unescape(text, True)
AttributeError: 'unicode' object has no attribute 'rawsource'
The full traceback has been saved in /tmp/sphinx-err-irAFO4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```